//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMdog.Lab1.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid RecId { get; set; }
        public byte[] RowVersion { get; set; }
        public string PersonId { get; set; }
        public string Idno { get; set; }
        public string EmpName { get; set; }
        public string EmpId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string DeptId { get; set; }
        public string DeptName { get; set; }
        public string AcrDeptId { get; set; }
        public string AcrDeptName { get; set; }
        public string TitleId { get; set; }
        public string TitleName { get; set; }
        public Nullable<System.DateTime> FirstDay { get; set; }
        public string StaffKind { get; set; }
        public string StaffKindDesc { get; set; }
        public string JobStatus { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
